name: CD

on:
  push:
    branches:
      - main
      - dev/*
      - feature/*
      - hotfix/*

jobs:
  init:
    runs-on: ubuntu-latest

    outputs:
      allow_prerelease: ${{ steps.set_values.outputs.allow_prerelease }}

    steps:
      - name: Set values

        id: set_values

        run: |
          echo "allow_prerelease=${{github.ref != 'refs/heads/main'}}" >> $GITHUB_ENV

  build:
    needs: init

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build

        shell: pwsh

        run: |
          Import-Module './scripts/CICD.DotNet.psm1'

          Build-Package `
            -Path './src/ClassLibrary1' `
            -AllowPrerelease:$${{ needs.init.outputs.allow_prerelease }}

  semantic_release:
    needs: build

    uses: ./.github/workflows/.semantic-release.yaml

    secrets: inherit

  publish:
    if: needs.semantic_release.outputs.new_release_published == 'true'

    needs:
      - init
      - semantic_release

    runs-on: ubuntu-latest

    steps:
      - run: echo ${{ needs.init.outputs.allow_prerelease }}