# This is a basic workflow to help you get started with Actions

name: CI-Publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      # prerelease:
      #   type: boolean
      #   # description: 'Whether to publish the package as a prerelease'
      #   required: false
      suffix:
        type: string
        # description: 'The suffix to append to the version number'
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Publish package
        env:
          NUGET_API_KEY: ${{secrets.GITHUB_TOKEN}}
        shell: pwsh
        run: |
          Import-Module './scripts/CI.DotNet.psm1'

          $parameterObject = @{
            Path = './src/ClassLibrary1'
            RegistryUri = 'https://nuget.pkg.github.com/${{github.repository_owner}}/index.json'
          }

          $prerelease = '${{github.event_name}}' -ieq 'workflow_dispatch'

          if ($prerelease) {
            $suffix = '${{inputs.suffix}}'

            if ([String]::IsNullOrEmpty($suffix)) {
              $suffix = '${{github.run_number}}'
            }

            $parameterObject.Suffix = $suffix
          }

          Publish-Package @parameterObject